# Quick Start (at fist stop ROS Master if working on host)
# $ docker compose -f compose.rosbot.mapping.yaml up

services:
  map-saver:
    image: husarion/nav2-map-server:humble-22-11-25
    network_mode: host
    ipc: host
    volumes:
      - ./maps:/maps
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: bash -c "while true; do ros2 run nav2_map_server map_saver_cli --free 0.15 --fmt png -f /maps/map; sleep 5; done"

  navigation:
    image: husarion/navigation2:humble-22-11-25
    restart: unless-stopped
    volumes:
      - ./config/nav2_params.yaml:/nav2_params.yaml
    command: >
      ros2 launch nav2_bringup navigation_launch.py
        params_file:=/nav2_params.yaml
        use_sim_time:=true

  mapping:
    image: husarion/slam-toolbox:humble-22-11-25
    container_name: slam-toolbox
    restart: unless-stopped
    volumes:
      - ./config/slam_params.yaml:/slam_params.yaml
      - ./maps:/maps
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=true
