# Quick Start
# $ xhost local:root
# $ docker compose -f compose.rviz.yaml up

services:
  rviz:
    image: husarion/rviz2:galactic
    container_name: rviz
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1

  joy2twist:
    image: husarion/joy2twist:galactic
    network_mode: host
    ipc: host
    devices:
      - /dev/input
    volumes:
      - ./config/joy2twist.yaml:/joy2twist.yaml
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: >
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml