# Quick Start
# $ xhost local:root
# $ docker compose -f compose.rosbot.webots.yaml up

services:

  webots:
    build: ..
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    runtime: nvidia
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
    command: >
      ros2 launch webots_ros2_husarion robot_launch.py
